export const actionIcons = [
  "Advanced Touch-ALC.png",
  "Advanced Touch-ARM.png",
  "Advanced Touch-BSM.png",
  "Advanced Touch-CRP.png",
  "Advanced Touch-CUL.png",
  "Advanced Touch-GSM.png",
  "Advanced Touch-LTW.png",
  "Advanced Touch-WVR.png",
  "Basic Synthesis-ALC.png",
  "Basic Synthesis-ARM.png",
  "Basic Synthesis-BSM.png",
  "Basic Synthesis-CRP.png",
  "Basic Synthesis-CUL.png",
  "Basic Synthesis-GSM.png",
  "Basic Synthesis-LTW.png",
  "Basic Synthesis-WVR.png",
  "Basic Touch-ALC.png",
  "Basic Touch-ARM.png",
  "Basic Touch-BSM.png",
  "Basic Touch-CRP.png",
  "Basic Touch-CUL.png",
  "Basic Touch-GSM.png",
  "Basic Touch-LTW.png",
  "Basic Touch-WVR.png",
  "Byregot's Blessing.png",
  "Careful Observation.png",
  "Careful Synthesis.png",
  "Delicate Synthesis-ALC.png",
  "Delicate Synthesis-ARM.png",
  "Delicate Synthesis-BSM.png",
  "Delicate Synthesis-CRP.png",
  "Delicate Synthesis-CUL.png",
  "Delicate Synthesis-GSM.png",
  "Delicate Synthesis-LTW.png",
  "Delicate Synthesis-WVR.png",
  "Final Appraisal.png",
  "Focused Synthesis-ALC.png",
  "Focused Synthesis-ARM.png",
  "Focused Synthesis-BSM.png",
  "Focused Synthesis-CRP.png",
  "Focused Synthesis-CUL.png",
  "Focused Synthesis-GSM.png",
  "Focused Synthesis-LTW.png",
  "Focused Synthesis-WVR.png",
  "Focused Touch-ALC.png",
  "Focused Touch-ARM.png",
  "Focused Touch-BSM.png",
  "Focused Touch-CRP.png",
  "Focused Touch-CUL.png",
  "Focused Touch-GSM.png",
  "Focused Touch-LTW.png",
  "Focused Touch-WVR.png",
  "Great Strides.png",
  "Groundwork-ALC.png",
  "Groundwork-ARM.png",
  "Groundwork-BSM.png",
  "Groundwork-CRP.png",
  "Groundwork-CUL.png",
  "Groundwork-GSM.png",
  "Groundwork-LTW.png",
  "Groundwork-WVR.png",
  "Hasty Touch.png",
  "Heart and Soul.png",
  "Innovation.png",
  "Intensive Synthesis-ALC.png",
  "Intensive Synthesis-ARM.png",
  "Intensive Synthesis-BSM.png",
  "Intensive Synthesis-CRP.png",
  "Intensive Synthesis-CUL.png",
  "Intensive Synthesis-GSM.png",
  "Intensive Synthesis-LTW.png",
  "Intensive Synthesis-WVR.png",
  "Manipulation.png",
  "Master's Mend.png",
  "Muscle Memory.png",
  "Observe.png",
  "Precise Touch-ALC.png",
  "Precise Touch-ARM.png",
  "Precise Touch-BSM.png",
  "Precise Touch-CRP.png",
  "Precise Touch-CUL.png",
  "Precise Touch-GSM.png",
  "Precise Touch-LTW.png",
  "Precise Touch-WVR.png",
  "Preparatory Touch-ALC.png",
  "Preparatory Touch-ARM.png",
  "Preparatory Touch-BSM.png",
  "Preparatory Touch-CRP.png",
  "Preparatory Touch-CUL.png",
  "Preparatory Touch-GSM.png",
  "Preparatory Touch-LTW.png",
  "Preparatory Touch-WVR.png",
  "Prudent Synthesis-ALC.png",
  "Prudent Synthesis-ARM.png",
  "Prudent Synthesis-BSM.png",
  "Prudent Synthesis-CRP.png",
  "Prudent Synthesis-CUL.png",
  "Prudent Synthesis-GSM.png",
  "Prudent Synthesis-LTW.png",
  "Prudent Synthesis-WVR.png",
  "Prudent Touch-ALC.png",
  "Prudent Touch-ARM.png",
  "Prudent Touch-BSM.png",
  "Prudent Touch-CRP.png",
  "Prudent Touch-CUL.png",
  "Prudent Touch-GSM.png",
  "Prudent Touch-LTW.png",
  "Prudent Touch-WVR.png",
  "Rapid Synthesis.png",
  "Reflect.png",
  "Standard Touch-ALC.png",
  "Standard Touch-ARM.png",
  "Standard Touch-BSM.png",
  "Standard Touch-CRP.png",
  "Standard Touch-CUL.png",
  "Standard Touch-GSM.png",
  "Standard Touch-LTW.png",
  "Standard Touch-WVR.png",
  "Trained Eye.png",
  "Trained Finesse.png",
  "Tricks of the Trade.png",
  "Veneration.png",
  "Waste Not II.png",
  "Waste Not.png",
];

export const statusIcons = [
  "Collectable Synthesis.png",
  "Comfort Zone.png",
  "Crafter's Soul.png",
  "Final Appraisal.png",
  "Great Strides.png",
  "Heart and Soul.png",
  "Ingenuity II.png",
  "Ingenuity.png",
  "Initial Preparations.png",
  "Inner Quiet-1.png",
  "Inner Quiet-10.png",
  "Inner Quiet-2.png",
  "Inner Quiet-3.png",
  "Inner Quiet-4.png",
  "Inner Quiet-5.png",
  "Inner Quiet-6.png",
  "Inner Quiet-7.png",
  "Inner Quiet-8.png",
  "Inner Quiet-9.png",
  "Innovation.png",
  "Maker's Mark.png",
  "Manipulation.png",
  "Muscle Memory.png",
  "Name of the Elements.png",
  "Nameless.png",
  "Reclaim.png",
  "Reusing.png",
  "Steady Hand II.png",
  "Steady Hand.png",
  "Stroke of Genius.png",
  "Veneration.png",
  "Waste Not II.png",
  "Waste Not.png",
  "Whistle-1.png",
  "Whistle-10.png",
  "Whistle-11.png",
  "Whistle-2.png",
  "Whistle-3.png",
  "Whistle-4.png",
  "Whistle-5.png",
  "Whistle-6.png",
  "Whistle-7.png",
  "Whistle-8.png",
  "Whistle-9.png",
];
