export const actionIcons = new Set([
  "Advanced Touch-ALC",
  "Advanced Touch-ARM",
  "Advanced Touch-BSM",
  "Advanced Touch-CRP",
  "Advanced Touch-CUL",
  "Advanced Touch-GSM",
  "Advanced Touch-LTW",
  "Advanced Touch-WVR",
  "Basic Synthesis-ALC",
  "Basic Synthesis-ARM",
  "Basic Synthesis-BSM",
  "Basic Synthesis-CRP",
  "Basic Synthesis-CUL",
  "Basic Synthesis-GSM",
  "Basic Synthesis-LTW",
  "Basic Synthesis-WVR",
  "Basic Touch-ALC",
  "Basic Touch-ARM",
  "Basic Touch-BSM",
  "Basic Touch-CRP",
  "Basic Touch-CUL",
  "Basic Touch-GSM",
  "Basic Touch-LTW",
  "Basic Touch-WVR",
  "Byregot's Blessing",
  "Careful Observation",
  "Careful Synthesis",
  "Delicate Synthesis-ALC",
  "Delicate Synthesis-ARM",
  "Delicate Synthesis-BSM",
  "Delicate Synthesis-CRP",
  "Delicate Synthesis-CUL",
  "Delicate Synthesis-GSM",
  "Delicate Synthesis-LTW",
  "Delicate Synthesis-WVR",
  "Final Appraisal",
  "Great Strides",
  "Groundwork-ALC",
  "Groundwork-ARM",
  "Groundwork-BSM",
  "Groundwork-CRP",
  "Groundwork-CUL",
  "Groundwork-GSM",
  "Groundwork-LTW",
  "Groundwork-WVR",
  "Hasty Touch",
  "Heart and Soul",
  "Immaculate Mend",
  "Innovation",
  "Intensive Synthesis-ALC",
  "Intensive Synthesis-ARM",
  "Intensive Synthesis-BSM",
  "Intensive Synthesis-CRP",
  "Intensive Synthesis-CUL",
  "Intensive Synthesis-GSM",
  "Intensive Synthesis-LTW",
  "Intensive Synthesis-WVR",
  "Manipulation",
  "Master's Mend",
  "Muscle Memory",
  "Observe",
  "Precise Touch-ALC",
  "Precise Touch-ARM",
  "Precise Touch-BSM",
  "Precise Touch-CRP",
  "Precise Touch-CUL",
  "Precise Touch-GSM",
  "Precise Touch-LTW",
  "Precise Touch-WVR",
  "Preparatory Touch-ALC",
  "Preparatory Touch-ARM",
  "Preparatory Touch-BSM",
  "Preparatory Touch-CRP",
  "Preparatory Touch-CUL",
  "Preparatory Touch-GSM",
  "Preparatory Touch-LTW",
  "Preparatory Touch-WVR",
  "Prudent Synthesis-ALC",
  "Prudent Synthesis-ARM",
  "Prudent Synthesis-BSM",
  "Prudent Synthesis-CRP",
  "Prudent Synthesis-CUL",
  "Prudent Synthesis-GSM",
  "Prudent Synthesis-LTW",
  "Prudent Synthesis-WVR",
  "Prudent Touch-ALC",
  "Prudent Touch-ARM",
  "Prudent Touch-BSM",
  "Prudent Touch-CRP",
  "Prudent Touch-CUL",
  "Prudent Touch-GSM",
  "Prudent Touch-LTW",
  "Prudent Touch-WVR",
  "Quick Innovation",
  "Rapid Synthesis",
  "Refined Touch-ALC",
  "Refined Touch-ARM",
  "Refined Touch-BSM",
  "Refined Touch-CRP",
  "Refined Touch-CUL",
  "Refined Touch-GSM",
  "Refined Touch-LTW",
  "Refined Touch-WVR",
  "Reflect",
  "Standard Touch-ALC",
  "Standard Touch-ARM",
  "Standard Touch-BSM",
  "Standard Touch-CRP",
  "Standard Touch-CUL",
  "Standard Touch-GSM",
  "Standard Touch-LTW",
  "Standard Touch-WVR",
  "Trained Eye",
  "Trained Finesse",
  "Trained Perfection",
  "Tricks of the Trade",
  "Veneration",
  "Waste Not",
  "Waste Not II",
]);

export const statusIcons = new Set([
  "Collectable Synthesis",
  "Comfort Zone",
  "Crafter's Soul",
  "Expedience",
  "Final Appraisal",
  "Great Strides",
  "Heart and Soul",
  "Ingenuity",
  "Ingenuity II",
  "Initial Preparations",
  "Inner Quiet-1",
  "Inner Quiet-10",
  "Inner Quiet-2",
  "Inner Quiet-3",
  "Inner Quiet-4",
  "Inner Quiet-5",
  "Inner Quiet-6",
  "Inner Quiet-7",
  "Inner Quiet-8",
  "Inner Quiet-9",
  "Innovation",
  "Maker's Mark",
  "Manipulation",
  "Muscle Memory",
  "Name of the Elements",
  "Nameless",
  "Reclaim",
  "Reusing",
  "Steady Hand",
  "Steady Hand II",
  "Stroke of Genius",
  "Trained Perfection",
  "Veneration",
  "Waste Not",
  "Waste Not II",
  "Whistle-1",
  "Whistle-10",
  "Whistle-11",
  "Whistle-2",
  "Whistle-3",
  "Whistle-4",
  "Whistle-5",
  "Whistle-6",
  "Whistle-7",
  "Whistle-8",
  "Whistle-9",
]);
