name: 'Deploy to Netlify'

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ 'CI' ]
    types: [ 'completed' ]
    branches: [ 'main', 'preview' ]

permissions:
  contents: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'

    - name: Get submodule commit hash
      id: get-submodule-hash
      run: echo "SUBMODULE_HASH=$(git submodule)" >> $GITHUB_OUTPUT

    - name: Check if submodule build is cached
      uses: actions/cache@v3
      id: submodule-cache
      with:
        path: crafty/web/pkg
        key: ${{ steps.get-submodule-hash.outputs.SUBMODULE_HASH }}

    - name: Build submodule
      if: steps.submodule-cache.outputs.cache-hit != 'true'
      # TODO: Update wasm-pack when install bug is fixed
      run: |
        yarn global add wasm-pack@0.10.3
        yarn run build-submodule

    - name: Install Node.js dependencies
      run: yarn install --frozen-lockfile

    - name: Build static files
      run: VITE_REVISION=$GITHUB_SHA yarn run build

    # https://cli.netlify.com/commands/deploy

    - name: Deploy to Netlify
      if: ${{ github.ref_name == 'main' }}
      env:
        AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      run: |
        yarn netlify deploy --auth $AUTH_TOKEN --site $SITE_ID --prod --dir dist \
          --message "$GITHUB_REF @ $GITHUB_SHA (attempt #$GITHUB_RUN_ATTEMPT)"

    - name: Deploy to Netlify (preview)
      if: ${{ github.ref_name == 'preview' }}
      env:
        AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      run: |
        yarn netlify deploy --auth $AUTH_TOKEN --site $SITE_ID --dir dist \
          --message "$GITHUB_REF @ $GITHUB_SHA (attempt #$GITHUB_RUN_ATTEMPT)"
